controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_base_controller:
      type: diff_drive_controller/DiffDriveController
      
    imu_broadcaster:
      type: imu_sensor_broadcaster/IMUSensorBroadcaster

joint_state_broadcaster:
  ros__parameters:
    joints:
      - rr_wheel_joint
      - rl_wheel_joint
      - fr_wheel_joint
      - fl_wheel_joint

imu_broadcaster:
  ros__parameters:
    sensor_name: imu
    frame_id: imu_link
    static_covariance_orientation: [1.9e-3, 0.0, 0.0, 0.0, 1.9e-3, 0.0, 0.0, 0.0, 1.9e-3]
    static_covariance_angular_velocity: [2.0e-3, 0.0, 0.0, 0.0, 2.0e-3, 0.0, 0.0, 0.0, 2.0e-3]
    static_covariance_linear_acceleration: [6.4e-2, 0.0, 0.0, 0.0, 2.2e-2, 0.0, 0.0, 0.0, 2.2e-2]


diff_drive_base_controller:
  ros__parameters:
    #testbot wheel joints
    left_wheel_names: ["fl_wheel_joint", "rl_wheel_joint"]
    right_wheel_names: ["fr_wheel_joint", "rr_wheel_joint"]
   
    #for Husa_test_desc
    #wheel_separation: 0.248
    #wheel_radius: 0.048

   #for testbot
    #wheel_separation: 0.32  # Corrected from 0.4 to match URDF (0.3m + 2 * 0.01m)
    #wheel_radius: 0.05     # Corrected from 0.1 to match URDF (radius, not diameter)

    #for 4w_testbot
    wheel_separation: 0.466
    wheel_radius: 0.1

    #for 4w.xacro
    #wheel_separation: 0.45  # Corrected from 0.4 to match URDF (0.3m + 2 * 0.01m)
    #wheel_radius: 0.1     # Corrected from 0.1 to match URDF (radius, not diameter)


    wheel_separation_multiplier: 1.265
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0

    publish_rate: 50.0
    odom_frame_id: odom
    base_frame_id: base_footprint
    pose_covariance_diagonal: [0.001, 0.001, 0.0, 0.0, 0.0, 0.01]
    twist_covariance_diagonal: [0.001, 0.0, 0.0, 0.0, 0.0, 0.01]
    #pose_covariance_diagonal: [0.01, 0.01, 0.1, 1.0, 1.0, 0.1]
    #twist_covariance_diagonal: [0.001, 0.001, 0.1, 1.0, 1.0, 0.01]
    
 

    open_loop: false 
    enable_odom_tf: true

    cmd_vel_timeout: 0.5
    use_stamped_vel: false
    velocity_rolling_window_size: 5

    linear.x.has_velocity_limits: true
    linear.x.has_acceleration_limits: true
    linear.x.has_jerk_limits: false
    linear.x.min_velocity: -1.0
    linear.x.max_acceleration: 1.0
    linear.x.max_jerk: 0.0
    linear.x.min_jerk: 0.0

    linear.x.max_velocity: 1.0

    angular.z.has_velocity_limits: true
    angular.z.has_acceleration_limits: true
    angular.z.has_jerk_limits: false
    angular.z.max_velocity: 0.5
    angular.z.min_velocity: -0.5
    angular.z.max_acceleration: 1.0
    angular.z.min_acceleration: -1.0
    angular.z.max_jerk: 0.0
    angular.z.min_jerk: 0.0

    #for testbot
    #linear.x.max_velocity: 0.5
  