twist_mux:
  ros__parameters:
    topics:
      teleop:
        topic   : cmd_vel
        timeout : 0.5
        priority: 100
      joystick:
        topic   : cmd_vel_joy
        timeout : 0.5
        priority: 80
      navigation:
        topic   : cmd_vel
        timeout : 0.5
        priority: 10
      
   